name: Lychee Link Checker

on: [pull_request]

jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --base https://docs.apify.com sources/ --verbose --no-progress './**/*.md' './**/*.mdx'
