name: Lychee Link Checker

on: [pull_request]

jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --base . --verbose --no-progress './**/*.md' './**/*.mdx'
