name: Test

on:
    push:
        branches: [ master, renovate/** ]
    pull_request:

jobs:
    build:
        name: Docs build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source code
                uses: actions/checkout@v4

            -   name: Use Node.js 22
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    always-auth: 'true'

            -   name: Enable corepack
                run: |
                    corepack enable
                    corepack prepare yarn@stable --activate
    
            -   name: Activate cache for Node.js
                uses: actions/setup-node@v4
                with:
                    cache: yarn
                    cache-dependency-path: yarn.lock

            -   name: Enable corepack
                run: |
                    corepack enable

            -   name: Install Dependencies
                run: yarn --immutable
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   run: yarn build
                env:
                    INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
                    SEGMENT_TOKEN: ${{ secrets.SEGMENT_TOKEN }}

    lint_content:
        name: Lint markdown content
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source code
                uses: actions/checkout@v4

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v46
                with:
                    files: '**/*.{md,mdx}'
                    files_ignore: '!sources/api/*.{md,mdx}'
                    separator: ","

            -   name: Use Node.js 22
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Enable corepack
                run: |
                    corepack enable
                    corepack prepare yarn@stable --activate
    
            -   name: Activate cache for Node.js
                uses: actions/setup-node@v4
                with:
                    cache: yarn
                    cache-dependency-path: yarn.lock

            -   name: Install Dependencies
                run: yarn --immutable
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: List and Lint Changed Markdown Files
                env:
                    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
                run: |
                    IFS=',' read -ra FILE_ARRAY <<< "$ALL_CHANGED_FILES"
                    for file in "${FILE_ARRAY[@]}"; do
                      npx markdownlint "$file"
                    done


    lint_code:
        name: Lint app code
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source code
                uses: actions/checkout@v4

            -   name: Use Node.js 22
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Enable corepack
                run: |
                    corepack enable
                    corepack prepare yarn@stable --activate
    
            -   name: Activate cache for Node.js
                uses: actions/setup-node@v4
                with:
                    cache: yarn
                    cache-dependency-path: yarn.lock

            -   name: Enable corepack
                run: |
                    corepack enable

            -   name: Install Dependencies
                run: yarn --immutable
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   run: yarn lint:code
